apiVersion: v1
kind: Service
metadata:
  name: hephaestus-gui
  namespace: hephaestus
spec:
  selector:
    app: hephaestus-gui
  type: LoadBalancer
  ports:
    - protocol: "TCP"
      port: 8080
      targetPort: 8080